#!/bin/bash

# ============================================================================
# bash_power_install.sh
# ============================================================================
# Advanced Bash Environment Installation Script
# Compatible: RHEL/CentOS/Fedora, Ubuntu/Debian
#
# FEATURES:
#   Core Tools:
#     - Starship: Cross-shell prompt with git integration
#     - fzf: Command-line fuzzy finder
#     - ble.sh: Bash Line Editor with syntax highlighting and auto-suggestions
#     - bash-completion: Programmable completion for bash
#   
#   Additional Tools:
#     - bat: cat clone with syntax highlighting
#     - ripgrep (rg): Ultra-fast text search tool
#     - fd: Fast alternative to 'find'
#     - tree, htop, ncdu: System utilities
#
# CONFIGURATION FILE STRUCTURE:
#   Main Configuration:
#     - ~/.bashrc                              (Generated, will be overwritten)
#     - ~/.bashrc.local                        (User config, NEVER overwritten)
#
#   Component Configurations (Unified Directory):
#     - ~/.config/bash-power/starship.toml    (Starship prompt config)
#     - ~/.config/bash-power/blerc            (ble.sh config)
#     - ~/.config/bash-power/bat.conf         (bat config)
#     - ~/.config/bash-power/ripgreprc        (ripgrep config)
#     - ~/.config/bash-power/aliases.bash     (Command aliases)
#     - ~/.config/bash-power/functions.bash   (Utility functions)
#     - ~/.config/bash-power/fzf.bash         (fzf config and functions)
#
#   Standard Tool Configs (Generated by tools):
#     - ~/.fzf.bash                           (fzf key bindings, auto-generated)
#
#   Backups:
#     - ~/.bash_config_backup_YYYYMMDD_HHMMSS/ (Timestamped backups)
#
# FILE PROTECTION POLICY:
#   PROTECTED (Never Overwritten):
#     - ~/.bashrc.local: Your personal configuration file
#       * Only created if it doesn't exist
#       * Safe to add: aliases, functions, environment variables, etc.
#       * Will NEVER be modified by this script
#   
#   MANAGED (Overwritten on Each Run):
#     - ~/.bashrc: Main bash configuration (auto-generated)
#     - ~/.config/bash-power/*: Component configurations
#     - All backed up before overwriting
#
# USAGE:
#   1. Run the script:
#      chmod +x bash_power_install.sh
#      ./bash_power_install.sh
#   
#   2. After installation:
#      source ~/.bashrc  # or restart your terminal
#   
#   3. Add personal configurations:
#      vim ~/.bashrc.local
#      # This file will NEVER be overwritten
#   
#   4. Re-run the script anytime to update configurations
#
# RESTORATION:
#   If you need to restore a previous configuration:
#     cp ~/.bash_config_backup_YYYYMMDD_HHMMSS/bashrc ~/.bashrc
#     source ~/.bashrc
#
# AUTHOR: Bash Power Environment Team
# LICENSE: MIT
# ============================================================================

# ============================================================================
# Global Variables and Version Configuration
# ============================================================================

# Tool versions (for manual installation when package manager fails)
readonly BAT_VERSION="0.24.0"
readonly RIPGREP_VERSION="14.1.0"
readonly FD_VERSION="9.0.0"

# Color definitions for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'  # No Color

# Configuration directory
readonly BASH_POWER_CONFIG_DIR="$HOME/.config/bash-power"

# Track temporary directories for cleanup
TEMP_DIRS=()

# ============================================================================
# Cleanup Handler
# ============================================================================
# This trap ensures temporary files are cleaned up even if script is interrupted

cleanup_temp_files() {
    if [ ${#TEMP_DIRS[@]} -gt 0 ]; then
        for tmp_dir in "${TEMP_DIRS[@]}"; do
            if [ -d "$tmp_dir" ]; then
                rm -rf "$tmp_dir"
            fi
        done
    fi
}

trap cleanup_temp_files EXIT INT TERM

# ============================================================================
# Logging Functions
# ============================================================================

log_info() { 
    echo -e "${BLUE}[INFO]${NC} $1" 
}

log_success() { 
    echo -e "${GREEN}[SUCCESS]${NC} $1" 
}

log_warning() { 
    echo -e "${YELLOW}[WARNING]${NC} $1" 
}

log_error() { 
    echo -e "${RED}[ERROR]${NC} $1" 
}

# ============================================================================
# System Detection Functions
# ============================================================================

# Detect Operating System Type
# Returns: "rhel", "ubuntu", or "unknown"
detect_os() {
    if [ -f /etc/redhat-release ]; then
        echo "rhel"
    elif [ -f /etc/lsb-release ] || [ -f /etc/debian_version ]; then
        echo "ubuntu"
    elif [ -f /etc/os-release ]; then
        source /etc/os-release
        if [[ $ID == "rhel" || $ID == "centos" || $ID == "fedora" ]]; then
            echo "rhel"
        elif [[ $ID == "ubuntu" || $ID == "debian" ]]; then
            echo "ubuntu"
        else
            echo "unknown"
        fi
    else
        echo "unknown"
    fi
}

# Detect package manager (dnf or yum)
# Returns: "dnf", "yum", or "none"
detect_package_manager() {
    if command -v dnf >/dev/null 2>&1; then
        echo "dnf"
    elif command -v yum >/dev/null 2>&1; then
        echo "yum"
    else
        echo "none"
    fi
}

# Check if command exists
# Usage: command_exists <command_name>
command_exists() { 
    command -v "$1" >/dev/null 2>&1
}

# Get Bash Version
# Returns: version string like "4.4" or "5.1"
# Note: Uses sed instead of grep -P for better compatibility
get_bash_version() {
    bash --version | head -n1 | sed -n 's/.*version \([0-9]\+\.[0-9]\+\).*/\1/p'
}

# Get RHEL version number
# Returns: major version number like "7", "8", "9"
get_rhel_version() {
    if [ -f /etc/redhat-release ]; then
        sed -n 's/.*release \([0-9]\+\).*/\1/p' /etc/redhat-release | head -n1
    else
        echo ""
    fi
}

# ============================================================================
# Prerequisite Checks
# ============================================================================

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    local missing_prereqs=()
    
    # Check for sudo privileges (test with a safe command)
    if ! sudo -n true 2>/dev/null; then
        if ! sudo true 2>/dev/null; then
            log_error "This script requires sudo privileges"
            return 1
        fi
    fi
    log_success "Sudo access confirmed"
    
    # Check for basic commands that we need before installing dependencies
    # We need at least one of these to bootstrap
    if ! command_exists curl && ! command_exists wget; then
        missing_prereqs+=("curl or wget")
    fi
    
    if [ ${#missing_prereqs[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing_prereqs[*]}"
        log_error "Please install these manually first"
        return 1
    fi
    
    # Check network connectivity
    log_info "Checking network connectivity..."
    if command_exists curl; then
        if ! curl -s --connect-timeout 5 https://www.google.com > /dev/null 2>&1; then
            log_warning "Network connectivity test failed"
            log_warning "You may need to configure proxy settings if behind a firewall"
            read -p "Continue anyway? (yes/NO): " -r response
            case "$response" in
                [yY][eE][sS]|[yY])
                    log_info "Continuing despite network issues..."
                    ;;
                *)
                    return 1
                    ;;
            esac
        else
            log_success "Network connectivity confirmed"
        fi
    fi
    
    return 0
}

# ============================================================================
# Binary Installation from GitHub
# ============================================================================

# Generic function to install binary from GitHub releases
# This is used as a fallback when package managers don't have the tools
#
# Usage: install_binary_from_github <tool_name> <download_url> <binary_name>
# Example: install_binary_from_github "bat" "https://..." "bat"
install_binary_from_github() {
    local tool_name="$1"
    local download_url="$2"
    local binary_name="$3"
    
    log_info "Downloading $tool_name from GitHub..."
    
    local tmp_dir
    tmp_dir=$(mktemp -d)
    TEMP_DIRS+=("$tmp_dir")
    
    cd "$tmp_dir" || return 1
    
    if curl -fsSL "$download_url" -o package.tar.gz; then
        if tar -xzf package.tar.gz 2>/dev/null; then
            # Find binary file in extracted contents
            local binary_path
            binary_path=$(find . -name "$binary_name" -type f | head -n 1)
            
            if [ -n "$binary_path" ]; then
                if sudo install -m 755 "$binary_path" /usr/local/bin/; then
                    log_success "$tool_name installed successfully"
                    cd - > /dev/null || true
                    return 0
                fi
            fi
        fi
    fi
    
    cd - > /dev/null || true
    log_error "$tool_name installation failed"
    return 1
}

# ============================================================================
# Dependency Installation
# ============================================================================

install_dependencies() {
    log_info "Installing system dependencies..."
    
    local os_type
    os_type=$(detect_os)
    log_info "Detected OS type: $os_type"
    
    case $os_type in
        "ubuntu"|"debian")
            install_dependencies_debian
            ;;
        "rhel"|"centos"|"fedora")
            install_dependencies_rhel
            ;;
        *)
            log_error "Unknown system type: $os_type"
            return 1
            ;;
    esac
    
    # Verify core dependencies
    log_info "Verifying core dependencies installation..."
    local missing_deps=()
    
    for dep in curl git; do
        if ! command_exists "$dep"; then
            missing_deps+=("$dep")
        fi
    done
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "The following core dependencies failed to install: ${missing_deps[*]}"
        return 1
    fi
    
    log_success "All core dependencies installed successfully"
    return 0
}

install_dependencies_debian() {
    log_info "Updating apt package list..."
    if ! sudo apt-get update; then
        log_warning "apt update failed, continuing with installation..."
    fi
    
    log_info "Installing core dependencies..."
    sudo apt-get install -y \
        curl \
        git \
        bash-completion \
        tree \
        htop \
        ncdu \
        wget \
        unzip \
        zip \
        make \
        build-essential \
        gawk
    
    # Try to install bash-completion extras (not critical)
    sudo apt-get install -y bash-completion-extras 2>/dev/null || \
        log_info "bash-completion-extras not available, skipping"
    
    # Try to install modern tools (allow failures, we'll install manually if needed)
    sudo apt-get install -y bat ripgrep fd-find 2>/dev/null || \
        log_warning "Some modern tools failed to install via apt, will use alternative methods"
    
    # Ubuntu calls fd "fdfind", create symlink if needed
    if command_exists fdfind && ! command_exists fd; then
        sudo ln -sf "$(which fdfind)" /usr/local/bin/fd
        log_success "Created fd symlink"
    fi
}

install_dependencies_rhel() {
    local pkg_mgr
    pkg_mgr=$(detect_package_manager)
    
    local rhel_version
    rhel_version=$(get_rhel_version)
    
    # Install EPEL repository for RHEL/CentOS
    if [ -n "$rhel_version" ] && [ "$rhel_version" -ge 7 ]; then
        log_info "Detected RHEL/CentOS $rhel_version, installing EPEL repository..."
        if [ "$pkg_mgr" = "dnf" ]; then
            sudo dnf install -y epel-release 2>/dev/null || \
                log_warning "EPEL installation failed"
        else
            sudo yum install -y epel-release 2>/dev/null || \
                log_warning "EPEL installation failed"
        fi
    fi
    
    log_info "Installing dependencies using $pkg_mgr..."
    
    if [ "$pkg_mgr" = "dnf" ]; then
        sudo dnf install -y \
            curl \
            git \
            bash-completion \
            tree \
            htop \
            ncdu \
            wget \
            unzip \
            zip \
            make \
            gcc \
            gcc-c++ \
            util-linux-user \
            gawk
        
        # Try to install modern tools
        sudo dnf install -y bat ripgrep fd-find 2>/dev/null || \
            log_warning "Some modern tools need manual installation"
    else
        sudo yum install -y \
            curl \
            git \
            bash-completion \
            tree \
            htop \
            ncdu \
            wget \
            unzip \
            zip \
            make \
            gcc \
            gcc-c++ \
            util-linux-user \
            gawk
    fi
    
    # RHEL7/CentOS7 special handling - manually install modern tools
    if [ "$rhel_version" = "7" ]; then
        log_info "RHEL/CentOS 7 detected, manually installing modern tools..."
        
        if ! command_exists bat; then
            install_binary_from_github "bat" \
                "https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/bat-v${BAT_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
                "bat"
        fi
        
        if ! command_exists rg; then
            install_binary_from_github "ripgrep" \
                "https://github.com/BurntSushi/ripgrep/releases/download/${RIPGREP_VERSION}/ripgrep-${RIPGREP_VERSION}-x86_64-unknown-linux-musl.tar.gz" \
                "rg"
        fi
        
        if ! command_exists fd; then
            install_binary_from_github "fd" \
                "https://github.com/sharkdp/fd/releases/download/v${FD_VERSION}/fd-v${FD_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
                "fd"
        fi
    fi
}

# ============================================================================
# Backup Configuration
# ============================================================================

backup_config() {
    log_info "Backing up existing configuration..."
    
    # Create backup directory with timestamp
    local backup_dir="$HOME/.bash_config_backup_$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$backup_dir"
    
    # Backup .bashrc (will be overwritten by this script)
    if [ -f ~/.bashrc ]; then
        cp ~/.bashrc "$backup_dir/bashrc"
        log_success "Backed up .bashrc"
    fi
    
    # Backup .bash_profile (may be modified)
    if [ -f ~/.bash_profile ]; then
        cp ~/.bash_profile "$backup_dir/bash_profile"
        log_success "Backed up .bash_profile"
    fi
    
    # Backup existing bash-power configurations
    if [ -d "$BASH_POWER_CONFIG_DIR" ]; then
        cp -r "$BASH_POWER_CONFIG_DIR" "$backup_dir/"
        log_success "Backed up existing bash-power configurations"
    fi
    
    # Clean up old backups (keep only last 5)
    local backup_dirs=($(ls -dt ~/.bash_config_backup_* 2>/dev/null || true))
    if [ ${#backup_dirs[@]} -gt 5 ]; then
        log_info "Cleaning up old backups (keeping last 5)..."
        for ((i=5; i<${#backup_dirs[@]}; i++)); do
            rm -rf "${backup_dirs[$i]}"
            log_info "Removed old backup: $(basename "${backup_dirs[$i]}")"
        done
    fi
    
    echo "Backup saved in: $backup_dir"
}

# ============================================================================
# Tool Installation Functions
# ============================================================================

# Install Starship Prompt
install_starship() {
    log_info "Installing Starship prompt..."
    
    if command_exists starship; then
        log_success "Starship already installed"
        return 0
    fi
    
    # Method 1: Use official installation script (preferred)
    log_info "Installing Starship using official script..."
    if curl -fsSL https://starship.rs/install.sh | sh -s -- -y; then
        log_success "Starship installation completed"
        return 0
    fi
    
    # Method 2: Use package manager
    log_info "Trying to install via package manager..."
    local os_type
    os_type=$(detect_os)
    
    case $os_type in
        "ubuntu"|"debian")
            if sudo apt install -y starship 2>/dev/null; then
                log_success "Starship installed via apt"
                return 0
            fi
            ;;
        "rhel"|"centos"|"fedora")
            local pkg_mgr
            pkg_mgr=$(detect_package_manager)
            if [ "$pkg_mgr" = "dnf" ] && sudo dnf install -y starship 2>/dev/null; then
                log_success "Starship installed via dnf"
                return 0
            elif [ "$pkg_mgr" = "yum" ] && sudo yum install -y starship 2>/dev/null; then
                log_success "Starship installed via yum"
                return 0
            fi
            ;;
    esac
    
    # Method 3: Manual binary download
    log_info "Trying manual Starship installation..."
    if sudo curl -fsSL https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz | \
       sudo tar -xzf - -C /usr/local/bin; then
        sudo chmod +x /usr/local/bin/starship
        log_success "Starship installed manually"
        return 0
    fi
    
    log_warning "Starship installation failed, will use fallback prompt"
    return 1
}

# Install fzf (Fuzzy Finder)
install_fzf() {
    log_info "Installing fzf (fuzzy finder)..."
    
    if command_exists fzf; then
        log_success "fzf already installed"
        return 0
    fi
    
    # Method 1: Use package manager
    local os_type
    os_type=$(detect_os)
    
    case $os_type in
        "ubuntu"|"debian")
            if sudo apt-get install -y fzf 2>/dev/null; then
                log_success "fzf installed via apt"
                return 0
            fi
            ;;
        "rhel"|"centos"|"fedora")
            local pkg_mgr
            pkg_mgr=$(detect_package_manager)
            if [ "$pkg_mgr" = "dnf" ] && sudo dnf install -y fzf 2>/dev/null; then
                log_success "fzf installed via dnf"
                return 0
            elif [ "$pkg_mgr" = "yum" ] && sudo yum install -y fzf 2>/dev/null; then
                log_success "fzf installed via yum"
                return 0
            fi
            ;;
    esac
    
    # Method 2: Install using Git
    log_info "Installing fzf using Git..."
    if ! command_exists git; then
        log_error "Git not available, cannot install fzf"
        return 1
    fi
    
    local fzf_dir="$HOME/.fzf"
    if [ -d "$fzf_dir" ]; then
        log_info "Updating existing fzf installation..."
        (cd "$fzf_dir" && git pull && ./install --all --no-update-rc)
    else
        log_info "Cloning fzf repository..."
        if git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_dir"; then
            "$fzf_dir/install" --all --no-update-rc
        else
            log_error "fzf clone failed"
            return 1
        fi
    fi
    
    if command_exists fzf; then
        log_success "fzf installation completed"
        return 0
    else
        log_warning "fzf installation failed"
        return 1
    fi
}

# Install ble.sh (Bash Line Editor)
install_blesh() {
    log_info "Installing ble.sh (Bash Line Editor)..."
    
    local blesh_dir="$HOME/.local/share/blesh"
    
    if [ -f "$blesh_dir/ble.sh" ]; then
        log_success "ble.sh already installed"
        return 0
    fi
    
    # Check Bash version
    local bash_version
    bash_version=$(get_bash_version)
    local bash_major
    bash_major=$(echo "$bash_version" | cut -d. -f1)
    
    if [ "$bash_major" -lt 4 ]; then
        log_warning "ble.sh requires Bash 4.0+, current: $bash_version, skipping installation"
        return 1
    fi
    
    log_info "Bash version $bash_version detected, proceeding with ble.sh installation..."
    
    # Ensure required dependencies are available
    if ! command_exists git; then
        log_error "Git not available, cannot install ble.sh"
        return 1
    fi
    
    if ! command_exists make; then
        log_error "Make not available, cannot install ble.sh"
        return 1
    fi
    
    # Create directory
    mkdir -p "$HOME/.local/share"
    
    log_info "Cloning ble.sh repository (this may take a moment)..."
    if git clone --recursive --depth 1 --shallow-submodules \
        https://github.com/akinomyoga/ble.sh.git "$blesh_dir" 2>/dev/null; then
        
        log_info "Building ble.sh..."
        if make -C "$blesh_dir" install PREFIX="$HOME/.local" 2>/dev/null; then
            log_success "ble.sh installed successfully"
            return 0
        else
            log_warning "ble.sh build failed, but files are available"
            return 0
        fi
    else
        log_error "ble.sh clone failed"
        return 1
    fi
}

# ============================================================================
# Configuration File Creation
# ============================================================================

# Create main bashrc configuration
create_bashrc() {
    log_info "Creating main bashrc configuration..."
    
    # Detect installed tools
    # Use a more robust detection that checks multiple locations
    # This handles cases where tools were just installed via package manager
    local has_fzf="false"
    if command_exists fzf || [ -x /usr/bin/fzf ] || [ -x /bin/fzf ]; then
        has_fzf="true"
    fi
    
    local has_bat="false"
    if command_exists bat || [ -x /usr/bin/bat ] || [ -x /bin/bat ]; then
        has_bat="true"
    fi
    
    local has_starship="false"
    if command_exists starship || [ -x /usr/local/bin/starship ] || [ -x /usr/bin/starship ] || [ -x /bin/starship ]; then
        has_starship="true"
    fi
    
    local has_blesh="false"
    if [ -f "$HOME/.local/share/blesh/ble.sh" ]; then
        has_blesh="true"
    fi
    
    local has_rg="false"
    if command_exists rg || [ -x /usr/bin/rg ] || [ -x /bin/rg ]; then
        has_rg="true"
    fi
    
    local has_fd="false"
    if command_exists fd || command_exists fdfind || [ -x /usr/bin/fd ] || [ -x /bin/fd ] || [ -x /usr/bin/fdfind ] || [ -x /bin/fdfind ]; then
        has_fd="true"
    fi
    
    local os_type
    os_type=$(detect_os)
    local bash_version
    bash_version=$(get_bash_version)
    
    cat > ~/.bashrc << 'EOF'
#!/bin/bash
# =============================================
# Advanced Bash Configuration
# Auto-generated by bash_power_install.sh
# =============================================
#
# DO NOT EDIT THIS FILE DIRECTLY
# For personal customizations, use: ~/.bashrc.local
#
# This file will be overwritten when you re-run the installation script.
# Any changes made here will be lost.
#
# For permanent customizations, add them to ~/.bashrc.local which is
# sourced at the end of this file and will never be overwritten.

EOF

    # Add generation metadata with variable expansion
    cat >> ~/.bashrc << METADATA_EOF
# Generated on: $(date)
# OS Type: $os_type
# Bash Version: $bash_version
# 
# Installed Tools:
#   Core:
#     - starship: $has_starship
#     - fzf: $has_fzf
#     - ble.sh: $has_blesh
#   Additional:
#     - bat: $has_bat
#     - ripgrep: $has_rg
#     - fd: $has_fd
# =============================================

METADATA_EOF

    # Add main configuration content
    cat >> ~/.bashrc << 'EOF'
# =============================================
# Non-Interactive Shell Check
# =============================================
# Return early if not running interactively
# This prevents output that would break rsync, scp, and other tools
# that use SSH to execute remote commands
[[ $- != *i* ]] && return

# =============================================
# Phase 1: ble.sh Early Loading
# =============================================
# ble.sh must be loaded early with --noattach flag
# It will be attached at the end of this file for proper initialization

if [[ $- == *i* ]] && [ -f ~/.local/share/blesh/ble.sh ]; then
    source ~/.local/share/blesh/ble.sh --noattach
fi

# =============================================
# Basic Environment Configuration
# =============================================

# Editor settings
export EDITOR='vim'
export VISUAL='vim'

# History configuration
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT="%F %T "

# Bash shell options
shopt -s histappend      # Append to history file, don't overwrite
shopt -s checkwinsize    # Update LINES and COLUMNS after each command
shopt -s globstar 2>/dev/null   # Enable ** recursive globbing (Bash 4+)
shopt -s cdspell 2>/dev/null    # Auto-correct cd typos
shopt -s dirspell 2>/dev/null   # Auto-correct directory spelling

# =============================================
# Component Configuration Paths
# =============================================
# All component configs are stored in unified directory

export BASH_POWER_CONFIG_DIR="$HOME/.config/bash-power"

# Set component-specific config paths
export STARSHIP_CONFIG="$BASH_POWER_CONFIG_DIR/starship.toml"
export BAT_CONFIG_PATH="$BASH_POWER_CONFIG_DIR/bat.conf"
export RIPGREP_CONFIG_PATH="$BASH_POWER_CONFIG_DIR/ripgreprc"

# =============================================
# Color Support
# =============================================

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Enable color support for ls and grep (preserve original commands)
if ls --color=auto &>/dev/null; then
    alias ls='ls --color=auto'
fi
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# =============================================
# Load Modular Configurations
# =============================================
# Each component has its own configuration file for better organization

# Load aliases (git, docker, npm, system utilities, etc.)
[ -f "$BASH_POWER_CONFIG_DIR/aliases.bash" ] && source "$BASH_POWER_CONFIG_DIR/aliases.bash"

# Load utility functions (mkcd, extract, qfind, etc.)
[ -f "$BASH_POWER_CONFIG_DIR/functions.bash" ] && source "$BASH_POWER_CONFIG_DIR/functions.bash"

# Load fzf configuration and functions (if installed)
[ -f "$BASH_POWER_CONFIG_DIR/fzf.bash" ] && source "$BASH_POWER_CONFIG_DIR/fzf.bash"

# Load fzf key bindings (generated by fzf installer)
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# =============================================
# Bash Completion
# =============================================
# Load bash-completion system
# Note: Individual completions are loaded on-demand for better performance

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  elif [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
  fi
fi

# =============================================
# Starship Prompt or Fallback
# =============================================

if command -v starship >/dev/null 2>&1; then
    # Use Starship prompt (modern, feature-rich)
    eval "$(starship init bash)"
else
    # Fallback to enhanced bash prompt with git branch
    parse_git_branch() {
        git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
    }
    
    # Color codes for prompt
    PS1_USER_COLOR='\[\033[01;32m\]'
    PS1_HOST_COLOR='\[\033[01;32m\]'
    PS1_PATH_COLOR='\[\033[01;34m\]'
    PS1_GIT_COLOR='\[\033[01;31m\]'
    PS1_RESET='\[\033[00m\]'
    
    PS1="${PS1_USER_COLOR}\u${PS1_RESET}@${PS1_HOST_COLOR}\h${PS1_RESET}:${PS1_PATH_COLOR}\w${PS1_GIT_COLOR}\$(parse_git_branch)${PS1_RESET}\$ "
fi

# =============================================
# Phase 2: ble.sh Attachment
# =============================================
# Attach ble.sh at the end for proper initialization

[[ ${BLE_VERSION-} ]] && ble-attach

# =============================================
# User Personal Configuration
# =============================================
# This file is for your personal customizations
# It will NEVER be overwritten by the installation script

[ -f ~/.bashrc.local ] && source ~/.bashrc.local

# =============================================
# Welcome Message
# =============================================
# Display system information and available tools

EOF

    # Add the welcome message function with dynamic detection
    cat >> ~/.bashrc << 'WELCOME_EOF'
# Function to display welcome message
bash_power_welcome() {
    echo
    echo "======================================================================="
    echo "  Advanced Bash Environment Loaded Successfully"
    echo "======================================================================="
    echo
    echo "System Information:"
    echo "  - OS: $(uname -s)"
    echo "  - Bash: $BASH_VERSION"
    echo "  - Editor: $EDITOR"
    echo "  - History: $HISTSIZE commands"
    echo
    echo "Core Tools:"
    
    # Dynamic detection of tools
    if command -v starship >/dev/null 2>&1; then
        echo "  [+] Starship Prompt: $(starship --version 2>/dev/null | head -n1 | awk '{print $2}')"
    else
        echo "  [-] Starship Prompt: not installed"
    fi
    
    if command -v fzf >/dev/null 2>&1; then
        echo "  [+] fzf Fuzzy Finder: $(fzf --version 2>/dev/null | awk '{print $1}')"
    else
        echo "  [-] fzf Fuzzy Finder: not installed"
    fi
    
    if [ -f ~/.local/share/blesh/ble.sh ]; then
        echo "  [+] ble.sh Line Editor: syntax highlight + auto-suggest enabled"
    else
        echo "  [-] ble.sh Line Editor: not installed"
    fi
    
    echo "  [+] bash-completion: smart tab completion enabled"
    echo
    echo "Additional Tools:"
    
    if command -v bat >/dev/null 2>&1; then
        echo "  [+] bat: syntax highlighting cat"
    else
        echo "  [ ] bat: not installed"
    fi
    
    if command -v rg >/dev/null 2>&1; then
        echo "  [+] ripgrep (rg): fast text search"
    else
        echo "  [ ] ripgrep (rg): not installed"
    fi
    
    if command -v fd >/dev/null 2>&1 || command -v fdfind >/dev/null 2>&1; then
        echo "  [+] fd: fast file finder"
    else
        echo "  [ ] fd: not installed"
    fi
WELCOME_EOF

    # Continue with the rest of welcome message
    cat >> ~/.bashrc << 'WELCOME_EOF4'
    echo
    echo "Configuration Files:"
    echo "  - Main config:     ~/.bashrc"
    echo "  - Personal config: ~/.bashrc.local (YOUR CUSTOMIZATIONS)"
    echo
    echo "  Components dir:  ~/.config/bash-power/"
    echo "    * starship.toml  (Starship prompt configuration)"
    echo "    * blerc          (ble.sh configuration)"
    echo "    * bat.conf       (bat configuration)"
    echo "    * ripgreprc      (ripgrep configuration)"
    echo "    * aliases.bash   (Command aliases)"
    echo "    * functions.bash (Utility functions)"
    echo "    * fzf.bash       (fzf custom env vars and functions)"
    echo
    echo "  Note: fzf key bindings are in ~/.fzf.bash (default location)"
    echo "        This file is auto-managed by fzf installer"
    echo
    echo "Quick Commands:"
    echo "  Git:    gst, gco, gc, gcm, gd, gps, gpl, gl, gla"
    echo "  Fuzzy:  fh (history), fcd (dir), fe (edit), fgl (git log), fkill"
    echo "  View:   ccat (colorful cat), bless (colorful less)"
    echo "  Docker: d, dc, dps, dex, dlogs"
    echo "  Utils:  mkcd, extract, qfind, psgrep"
    echo
    echo "Keyboard Shortcuts:"
    echo "  Ctrl+R      Fuzzy history search"
    echo "  Ctrl+T      Fuzzy file search"
    echo "  Alt+C       Fuzzy directory search"
    echo "  Tab         Intelligent completion"
    echo
    echo "Tips:"
    echo "  - Commands have real-time syntax highlighting"
    echo "  - Use arrow keys for history with auto-suggestions"
    echo "  - Add personal configs to ~/.bashrc.local (never overwritten)"
    echo "  - Customize prompt in ~/.config/bash-power/starship.toml"
    echo "  - Run 'source ~/.bashrc' to reload configuration"
    echo
    echo "======================================================================="
    echo
}

# Call welcome message
bash_power_welcome
WELCOME_EOF4

    log_success "Main bashrc created successfully"
}

# Create aliases configuration file
create_aliases_config() {
    log_info "Creating aliases configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/aliases.bash" << 'EOF'
#!/bin/bash
# =============================================
# Bash Power - Command Aliases
# =============================================
# This file contains all command aliases
# Auto-generated by bash_power_install.sh
#
# For personal aliases, add them to ~/.bashrc.local

# =============================================
# Core File Listing Aliases
# =============================================

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -laht'        # Sort by time, newest first
alias ltr='ls -lahtr'      # Sort by time, oldest first
alias lss='ls -lhSr'       # Sort by size

# =============================================
# bat Integration (Non-Destructive)
# =============================================
# We don't override 'cat', but provide enhanced alternatives

if command -v bat >/dev/null 2>&1; then
    alias ccat='bat --paging=never'           # Colorful cat
    alias bless='bat --paging=always'         # Colorful less
    alias bathelp='bat --plain --language=help'
    
    # Enhanced man pages with bat
    if command -v batcat >/dev/null 2>&1; then
        export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
    else
        export MANPAGER="sh -c 'col -bx | bat -l man -p'"
    fi
fi

# =============================================
# Git Aliases
# =============================================

alias gst='git status'
alias gco='git checkout'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gaa='git add .'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gl='git log --oneline --graph --decorate'
alias gla='git log --oneline --graph --decorate --all'
alias gll='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gps='git push'
alias gpl='git pull'
alias gf='git fetch'
alias gfp='git fetch --prune'
alias gcl='git clone'
alias gsw='git switch'
alias gswc='git switch -c'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gm='git merge'
alias gsh='git stash'
alias gshp='git stash pop'
alias gshl='git stash list'

# =============================================
# Directory Navigation
# =============================================

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'

# Quick directory bookmarks
alias cdl='cd ~/.local'
alias cdc='cd ~/.config'
alias cdd='cd ~/Downloads'
alias cdh='cd ~'

# =============================================
# Docker Aliases
# =============================================

alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias dpa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlogs='docker logs -f'

# =============================================
# NPM/Yarn Aliases
# =============================================

alias nr='npm run'
alias ni='npm install'
alias nid='npm install --save-dev'
alias ns='npm start'
alias nt='npm test'
alias nci='npm ci'
alias y='yarn'
alias yr='yarn run'
alias ys='yarn start'
alias yi='yarn install'

# =============================================
# Python Aliases
# =============================================

alias py='python3'
alias pip='pip3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate || source .venv/bin/activate'

# =============================================
# System Monitoring Aliases
# =============================================

alias cpucore='grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo "unknown"'
alias meminfo='free -h 2>/dev/null || top -l 1 | grep PhysMem'
alias diskusage='df -h'
alias folderusage='du -sh ./* 2>/dev/null | sort -hr'
alias ports='netstat -tulanp 2>/dev/null || ss -tulanp'
alias myip='curl -s https://ifconfig.me'
alias localip='hostname -I 2>/dev/null || ipconfig getifaddr en0'

EOF

    log_success "Aliases configuration created"
}

# Create functions configuration file
create_functions_config() {
    log_info "Creating functions configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/functions.bash" << 'EOF'
#!/bin/bash
# =============================================
# Bash Power - Utility Functions
# =============================================
# This file contains utility functions
# Auto-generated by bash_power_install.sh
#
# For personal functions, add them to ~/.bashrc.local

# =============================================
# Directory Management
# =============================================

# Create directory and cd into it
# Usage: mkcd <directory_name>
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# =============================================
# Archive Extraction
# =============================================

# Extract various archive formats automatically
# Usage: extract <archive_file>
# Supports: tar.gz, tar.bz2, zip, rar, 7z, gz, bz2, etc.
extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"     ;;
            *.tar.gz)    tar xzf "$1"     ;;
            *.tar.xz)    tar xJf "$1"     ;;
            *.bz2)       bunzip2 "$1"     ;;
            *.rar)       unrar x "$1"     ;;
            *.gz)        gunzip "$1"      ;;
            *.tar)       tar xf "$1"      ;;
            *.tbz2)      tar xjf "$1"     ;;
            *.tgz)       tar xzf "$1"     ;;
            *.zip)       unzip "$1"       ;;
            *.Z)         uncompress "$1"  ;;
            *.7z)        7z x "$1"        ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# =============================================
# File Search
# =============================================

# Quick find files by name (case-insensitive)
# Usage: qfind <filename_pattern>
qfind() {
    find . -iname "*$1*"
}

# =============================================
# Process Management
# =============================================

# Grep through running processes
# Usage: psgrep <process_name>
psgrep() {
    ps aux | grep -v grep | grep -i -e VSZ -e "$1"
}

EOF

    log_success "Functions configuration created"
}

# Create fzf configuration file
create_fzf_config() {
    log_info "Creating fzf configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    # Determine fd command name (Ubuntu uses fdfind)
    local fd_cmd="fd"
    if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
        fd_cmd="fdfind"
    fi
    
    cat > "$BASH_POWER_CONFIG_DIR/fzf.bash" << FZFEOF
#!/bin/bash
# =============================================
# Bash Power - fzf Configuration
# =============================================
# This file contains fzf configuration and custom functions
# Auto-generated by bash_power_install.sh
#
# For personal fzf configs, add them to ~/.bashrc.local

# =============================================
# fzf Environment Variables
# =============================================

# Default options for fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --inline-info'

# Default command for fzf (file search)
export FZF_DEFAULT_COMMAND='$fd_cmd --type f --hidden --follow --exclude .git 2>/dev/null || find . -type f'

# Command for Ctrl+T (file search)
export FZF_CTRL_T_COMMAND="\$FZF_DEFAULT_COMMAND"

# Command for Alt+C (directory search)
export FZF_ALT_C_COMMAND='$fd_cmd --type d --hidden --follow --exclude .git 2>/dev/null || find . -type d'

# =============================================
# fzf Custom Functions
# =============================================

# Search command history with fzf
# Usage: fh
fh() {
    local selected_command
    selected_command=\$(history | fzf +s --tac --tiebreak=index | sed 's/ *[0-9]* *//')
    if [ -n "\$selected_command" ]; then
        eval "\$selected_command"
    fi
}

# Navigate to directory with fzf
# Usage: fcd
fcd() {
    local dir
    dir=\$($fd_cmd --type d --hidden --follow --exclude .git 2>/dev/null | fzf --preview 'tree -C {} | head -50')
    [ -n "\$dir" ] && cd "\$dir"
}

# Search and edit file with fzf
# Usage: fe
fe() {
    local file
    file=\$(fzf --preview 'bat --color=always --line-range :500 {} 2>/dev/null || cat {}')
    [ -n "\$file" ] && \${EDITOR:-vim} "\$file"
}

# Kill process with fzf
# Usage: fkill [signal]
fkill() {
    local pid
    pid=\$(ps aux | sed 1d | fzf -m | awk '{print \$2}')
    if [ -n "\$pid" ]; then
        echo "\$pid" | xargs kill -\${1:-9}
    fi
}

# Checkout git branch with fzf
# Usage: fgb
fgb() {
    local branch
    branch=\$(git branch --all | grep -v HEAD | sed 's/^..//' | sed 's#remotes/origin/##' | sort -u | fzf)
    [ -n "\$branch" ] && git checkout "\$branch"
}

# Browse git log with fzf
# Usage: fgl
fgl() {
    git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "\$@" | \\
    fzf --ansi --no-sort --reverse --tiebreak=index --preview \\
    'echo {} | grep -o "[a-f0-9]\{7\}" | head -1 | xargs -I % git show --color=always %' \\
    --bind "enter:execute:echo {} | grep -o '[a-f0-9]\{7\}' | head -1 | xargs -I % git show --color=always % | less -R"
}

FZFEOF

    log_success "fzf configuration created"
}

# Create Starship configuration
create_starship_config() {
    log_info "Creating Starship configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/starship.toml" << 'EOF'
# =============================================
# Starship Configuration
# =============================================
# This file configures the Starship prompt
# Auto-generated by bash_power_install.sh
#
# To customize, edit this file directly
# Docs: https://starship.rs/config/

# Overall format - defines what appears in the prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$line_break\
$jobs\
$character"""

# Prompt character (changes on error)
[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

# Directory display
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"
read_only = " [RO]"
read_only_style = "red"

# Git branch
[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "bold purple"

# Git status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "^${count}"
behind = "v${count}"
diverged = "^${ahead_count}v${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = ">>${count}"
deleted = "x${count}"
style = "bold yellow"

# Git state (rebase, merge, etc.)
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bright-black"

# Command duration
[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "bold yellow"

# Background jobs
[jobs]
symbol = "*"
style = "bold blue"
number_threshold = 1

# Username (shown when relevant)
[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = false

# Hostname (shown for SSH sessions)
[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold green"
disabled = false

EOF

    log_success "Starship configuration created"
}

# Create ble.sh configuration
create_blesh_config() {
    log_info "Creating ble.sh configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/blerc" << 'EOF'
# =============================================
# ble.sh Configuration
# =============================================
# This file configures ble.sh (Bash Line Editor)
# Auto-generated by bash_power_install.sh
#
# To customize, edit this file directly
# Docs: https://github.com/akinomyoga/ble.sh

# History settings
bleopt history_share=1

# Auto-complete settings
bleopt complete_auto_delay=300

EOF

    # Create symlink to standard location if ble.sh is installed
    if [ -f "$HOME/.local/share/blesh/ble.sh" ]; then
        ln -sf "$BASH_POWER_CONFIG_DIR/blerc" "$HOME/.blerc"
        log_info "Created symlink: ~/.blerc -> ~/.config/bash-power/blerc"
    fi
    
    log_success "ble.sh configuration created"
}

# Create bat configuration
create_bat_config() {
    log_info "Creating bat configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/bat.conf" << 'EOF'
# =============================================
# bat Configuration
# =============================================
# This file configures bat (cat with syntax highlighting)
# Auto-generated by bash_power_install.sh
#
# To customize, edit this file directly
# Docs: https://github.com/sharkdp/bat

# Theme
--theme="Monokai Extended"

# Show line numbers and Git modifications
--style="numbers,changes"

# Use italic text on the terminal
--italic-text=always

# Add mouse scrolling support
--paging=auto

EOF

    log_success "bat configuration created"
}

# Create ripgrep configuration
create_ripgrep_config() {
    log_info "Creating ripgrep configuration..."
    
    mkdir -p "$BASH_POWER_CONFIG_DIR"
    
    cat > "$BASH_POWER_CONFIG_DIR/ripgreprc" << 'EOF'
# =============================================
# ripgrep Configuration
# =============================================
# This file configures ripgrep (fast text search)
# Auto-generated by bash_power_install.sh
#
# To customize, edit this file directly
# Docs: https://github.com/BurntSushi/ripgrep

# Always use smart case searching
--smart-case

# Show line numbers
--line-number

# Follow symbolic links
--follow

# Search hidden files and directories
--hidden

# Don't search in .git directories
--glob=!.git/*

EOF

    log_success "ripgrep configuration created"
}

# Create user personal configuration file
create_bashrc_local() {
    log_info "Checking personal configuration file..."
    
    # Only create if it doesn't exist (NEVER overwrite)
    if [ ! -f ~/.bashrc.local ]; then
        cat > ~/.bashrc.local << 'EOF'
#!/bin/bash
# =============================================
# Personal Bash Configuration
# =============================================
# This file is for your custom configurations
#
# IMPORTANT: This file will NEVER be modified or overwritten by
#            the bash_power_install.sh script.
#            It is safe to add all your personal configurations here.
#
# This file is automatically sourced by ~/.bashrc

# =============================================
# Environment Variables
# =============================================
# Examples:
# export EDITOR='nvim'
# export GOPATH="$HOME/go"
# export PATH="$HOME/.local/bin:$PATH"

# =============================================
# Personal Aliases
# =============================================
# Examples:
# alias myserver='ssh user@server.com'
# alias myproject='cd ~/projects/myproject'

# =============================================
# Custom Functions
# =============================================
# Examples:
# cdl() {
#     cd "$1" && ls
# }
#
# backup() {
#     tar czf "$1.tar.gz" "$1"
# }

# =============================================
# Additional Configurations
# =============================================
# Add any other bash configurations here:
# - shopt options
# - bind commands
# - prompt customization
# - source other configuration files

EOF
        chmod 600 ~/.bashrc.local
        log_success "Created personal config file: ~/.bashrc.local"
    else
        log_info "Personal config file ~/.bashrc.local already exists (preserved)"
    fi
}

# ============================================================================
# Installation Verification
# ============================================================================

verify_installation() {
    log_info "Verifying installation results..."
    
    echo
    echo "======================================================================="
    echo "  Installation Verification Report"
    echo "======================================================================="
    echo
    
    local os_type
    os_type=$(detect_os)
    local bash_version
    bash_version=$(get_bash_version)
    
    echo "System Information:"
    echo "  - OS Type: $os_type"
    echo "  - Bash Version: $bash_version"
    echo
    
    echo "Core Tools:"
    if command_exists starship; then
        echo "  [+] Starship: $(starship --version | head -n1)"
    else
        echo "  [-] Starship: Not installed"
    fi
    
    if command_exists fzf; then
        echo "  [+] fzf: $(fzf --version)"
    else
        echo "  [-] fzf: Not installed"
    fi
    
    if [ -f "$HOME/.local/share/blesh/ble.sh" ]; then
        echo "  [+] ble.sh: Installed"
    else
        echo "  [-] ble.sh: Not installed"
    fi
    
    if [ -f /usr/share/bash-completion/bash_completion ] || [ -f /etc/bash_completion ]; then
        echo "  [+] bash-completion: Installed"
    else
        echo "  [-] bash-completion: Not installed"
    fi
    
    echo
    echo "Additional Tools:"
    # Use robust detection checking multiple paths
    if command_exists bat || [ -x /usr/bin/bat ] || [ -x /bin/bat ]; then
        echo "  [+] bat: $(bat --version 2>/dev/null | head -n1 || /usr/bin/bat --version 2>/dev/null | head -n1 || /bin/bat --version 2>/dev/null | head -n1 || echo 'installed')"
    else
        echo "  [-] bat: Not installed"
    fi
    
    if command_exists rg || [ -x /usr/bin/rg ] || [ -x /bin/rg ]; then
        echo "  [+] ripgrep: $(rg --version 2>/dev/null | head -n1 || /usr/bin/rg --version 2>/dev/null | head -n1 || /bin/rg --version 2>/dev/null | head -n1 || echo 'installed')"
    else
        echo "  [-] ripgrep: Not installed"
    fi
    
    if command_exists fd || command_exists fdfind || [ -x /usr/bin/fd ] || [ -x /bin/fd ] || [ -x /usr/bin/fdfind ] || [ -x /bin/fdfind ]; then
        echo "  [+] fd: Installed"
    else
        echo "  [-] fd: Not installed"
    fi
    
    echo
    echo "Configuration Files:"
    [ -f ~/.bashrc ] && echo "  [+] ~/.bashrc: Created" || echo "  [-] ~/.bashrc: Failed"
    [ -f ~/.bashrc.local ] && echo "  [+] ~/.bashrc.local: Ready" || echo "  [-] ~/.bashrc.local: Missing"
    [ -d "$BASH_POWER_CONFIG_DIR" ] && echo "  [+] $BASH_POWER_CONFIG_DIR: Created" || echo "  [-] Component configs: Missing"
    
    if [ -d "$BASH_POWER_CONFIG_DIR" ]; then
        echo
        echo "  Component Configuration Files:"
        [ -f "$BASH_POWER_CONFIG_DIR/starship.toml" ] && echo "    [+] starship.toml"
        [ -f "$BASH_POWER_CONFIG_DIR/blerc" ] && echo "    [+] blerc"
        [ -f "$BASH_POWER_CONFIG_DIR/bat.conf" ] && echo "    [+] bat.conf"
        [ -f "$BASH_POWER_CONFIG_DIR/ripgreprc" ] && echo "    [+] ripgreprc"
        [ -f "$BASH_POWER_CONFIG_DIR/aliases.bash" ] && echo "    [+] aliases.bash"
        [ -f "$BASH_POWER_CONFIG_DIR/functions.bash" ] && echo "    [+] functions.bash"
        [ -f "$BASH_POWER_CONFIG_DIR/fzf.bash" ] && echo "    [+] fzf.bash"
    fi
    
    echo
    echo "======================================================================="
    echo "  Installation Completed Successfully"
    echo "======================================================================="
    echo
    echo "Next Steps:"
    echo "  1. Run: source ~/.bashrc"
    echo "  2. Or restart your terminal"
    echo
    echo "Test Commands:"
    echo "  - gst       Git status"
    echo "  - fh        Fuzzy history search"
    echo "  - fcd       Fuzzy directory navigation"
    echo "  - fe        Fuzzy file edit"
    echo "  - ccat      Colorful cat (bat)"
    echo "  - fgl       Fuzzy git log browser"
    echo
    echo "Customization:"
    echo "  - Edit ~/.bashrc.local for personal configurations"
    echo "  - Edit ~/.config/bash-power/starship.toml for prompt customization"
    echo "  - Edit other files in ~/.config/bash-power/ for component configs"
    echo
    echo "Key Features:"
    echo "  - Syntax highlighting and auto-suggestions (ble.sh)"
    echo "  - Fuzzy finding for files, directories, history (fzf)"
    echo "  - Beautiful prompt with git integration (starship)"
    echo "  - Extensive aliases and functions"
    echo "  - Smart completion (bash-completion)"
    echo
}

# ============================================================================
# Main Execution Flow
# ============================================================================

main() {
    echo "======================================================================="
    echo "  Bash Power Environment Installation"
    echo "======================================================================="
    echo
    
    # Check prerequisites
    if ! check_prerequisites; then
        log_error "Prerequisites check failed, exiting"
        exit 1
    fi
    
    local os_type
    os_type=$(detect_os)
    log_info "Detected system type: $os_type"
    
    if [ "$os_type" = "unknown" ]; then
        log_error "Unrecognized operating system type, exiting"
        exit 1
    fi
    
    # Check Bash version
    local bash_version
    bash_version=$(get_bash_version)
    log_info "Bash version: $bash_version"
    
    # Install all dependencies first
    if ! install_dependencies; then
        log_error "Dependency installation failed, exiting"
        exit 1
    fi
    
    # Backup existing configuration
    backup_config
    
    # Install core tools (allow partial failures)
    install_starship || log_warning "Starship installation failed, will use basic prompt"
    install_fzf || log_warning "fzf installation failed, some features unavailable"
    install_blesh || log_warning "ble.sh installation failed, no line editing enhancements"
    
    # Create all configuration files
    create_bashrc || { log_error "Failed to create main bashrc"; exit 1; }
    create_aliases_config || log_warning "Failed to create aliases config"
    create_functions_config || log_warning "Failed to create functions config"
    
    if command_exists fzf; then
        create_fzf_config || log_warning "Failed to create fzf config"
    fi
    
    if command_exists starship; then
        create_starship_config || log_warning "Failed to create starship config"
    fi
    
    if [ -f "$HOME/.local/share/blesh/ble.sh" ]; then
        create_blesh_config || log_warning "Failed to create ble.sh config"
    fi
    
    if command_exists bat; then
        create_bat_config || log_warning "Failed to create bat config"
    fi
    
    if command_exists rg; then
        create_ripgrep_config || log_warning "Failed to create ripgrep config"
    fi
    
    # Create user personal config (only if doesn't exist)
    create_bashrc_local
    
    # Verify and display results
    verify_installation
    
    log_success "All components installed successfully"
    
    echo "Installation complete. Enjoy your enhanced Bash environment!"
}

# Execute main function
main "$@"
